spring:
  profiles:
    active: production

  server:
    port: 8080
    address: 127.0.0.1

  freemarker:
    exposeSessionAttributes: true

security:
  user:
    role: ADMIN
    name: admin
    password: admin
  enableCsrf: true

http:
  mappers:
    jsonPrettyPrint: true

---
spring:
  profiles: development

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:./h2data;MODE=MySQL
    username: sa
    password: sa

  jpa:
    generateDdl: true

---
spring:
  profiles: production

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mongoreporter?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    generateDdl: true